//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  user: User;
  authenticate?: Maybe<UserUsers>;
  authorize?: Maybe<UserUsers>;
  userConnection: UserConnection;
  siteSettings: SiteSettings;
  siteSettingsConnection: SiteSettingsConnection;
  homePage: HomePage;
  homePageConnection: HomePageConnection;
  project: Project;
  projectConnection: ProjectConnection;
  testimonial: Testimonial;
  testimonialConnection: TestimonialConnection;
  post: Post;
  postConnection: PostConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryUserArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAuthenticateArgs = {
  sub: Scalars['String']['input'];
  password: Scalars['String']['input'];
};


export type QueryUserConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<UserFilter>;
};


export type QuerySiteSettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
};


export type QueryHomePageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomePageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageFilter>;
};


export type QueryProjectArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
};


export type QueryTestimonialArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonialConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialFilter>;
};


export type QueryPostArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
};

export type DocumentFilter = {
  user?: InputMaybe<UserFilter>;
  siteSettings?: InputMaybe<SiteSettingsFilter>;
  homePage?: InputMaybe<HomePageFilter>;
  project?: InputMaybe<ProjectFilter>;
  testimonial?: InputMaybe<TestimonialFilter>;
  post?: InputMaybe<PostFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = User | SiteSettings | HomePage | Project | Testimonial | Post | Folder;

export type UserUsersPassword = {
  __typename?: 'UserUsersPassword';
  value: Scalars['String']['output'];
  passwordChangeRequired?: Maybe<Scalars['Boolean']['output']>;
};

export type UserUsers = {
  __typename?: 'UserUsers';
  username: Scalars['String']['output'];
  name?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  password: UserUsersPassword;
};

export type User = Node & Document & {
  __typename?: 'User';
  users?: Maybe<Array<Maybe<UserUsers>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type UserUsersFilter = {
  username?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
};

export type UserFilter = {
  users?: InputMaybe<UserUsersFilter>;
};

export type UserConnectionEdges = {
  __typename?: 'UserConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<User>;
};

export type UserConnection = Connection & {
  __typename?: 'UserConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<UserConnectionEdges>>>;
};

export type SiteSettingsNavItems = {
  __typename?: 'SiteSettingsNavItems';
  label: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type SiteSettingsNavCta = {
  __typename?: 'SiteSettingsNavCta';
  label: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type SiteSettingsFooterPrimaryCta = {
  __typename?: 'SiteSettingsFooterPrimaryCta';
  label: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type SiteSettingsSocialLinks = {
  __typename?: 'SiteSettingsSocialLinks';
  label: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type SiteSettings = Node & Document & {
  __typename?: 'SiteSettings';
  siteName: Scalars['String']['output'];
  siteUrl: Scalars['String']['output'];
  defaultTitle: Scalars['String']['output'];
  titleTemplate: Scalars['String']['output'];
  description: Scalars['String']['output'];
  abstract: Scalars['String']['output'];
  keywords: Array<Scalars['String']['output']>;
  creator: Scalars['String']['output'];
  publisher: Scalars['String']['output'];
  category: Scalars['String']['output'];
  themeColor: Scalars['String']['output'];
  ogImage: Scalars['String']['output'];
  twitterHandle: Scalars['String']['output'];
  navItems?: Maybe<Array<Maybe<SiteSettingsNavItems>>>;
  navCta?: Maybe<SiteSettingsNavCta>;
  footerMarqueeText: Scalars['String']['output'];
  footerPrimaryCta?: Maybe<SiteSettingsFooterPrimaryCta>;
  socialLinks?: Maybe<Array<Maybe<SiteSettingsSocialLinks>>>;
  footerCopyright: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteSettingsNavItemsFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type SiteSettingsNavCtaFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type SiteSettingsFooterPrimaryCtaFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type SiteSettingsSocialLinksFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type SiteSettingsFilter = {
  siteName?: InputMaybe<StringFilter>;
  siteUrl?: InputMaybe<StringFilter>;
  defaultTitle?: InputMaybe<StringFilter>;
  titleTemplate?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  abstract?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
  creator?: InputMaybe<StringFilter>;
  publisher?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  themeColor?: InputMaybe<StringFilter>;
  ogImage?: InputMaybe<ImageFilter>;
  twitterHandle?: InputMaybe<StringFilter>;
  navItems?: InputMaybe<SiteSettingsNavItemsFilter>;
  navCta?: InputMaybe<SiteSettingsNavCtaFilter>;
  footerMarqueeText?: InputMaybe<StringFilter>;
  footerPrimaryCta?: InputMaybe<SiteSettingsFooterPrimaryCtaFilter>;
  socialLinks?: InputMaybe<SiteSettingsSocialLinksFilter>;
  footerCopyright?: InputMaybe<StringFilter>;
};

export type SiteSettingsConnectionEdges = {
  __typename?: 'SiteSettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteSettings>;
};

export type SiteSettingsConnection = Connection & {
  __typename?: 'SiteSettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteSettingsConnectionEdges>>>;
};

export type HomePageHero = {
  __typename?: 'HomePageHero';
  mobileHeadline: Scalars['String']['output'];
  curvedHeadline: Scalars['String']['output'];
  eyebrow: Scalars['String']['output'];
  description: Scalars['String']['output'];
  primaryCtaLabel: Scalars['String']['output'];
  primaryCtaUrl: Scalars['String']['output'];
};

export type HomePageFeatureShowcaseSlides = {
  __typename?: 'HomePageFeatureShowcaseSlides';
  image: Scalars['String']['output'];
  title: Scalars['String']['output'];
};

export type HomePageFeatureShowcase = {
  __typename?: 'HomePageFeatureShowcase';
  headingPrefix: Scalars['String']['output'];
  highlightWord: Scalars['String']['output'];
  description: Scalars['String']['output'];
  slides?: Maybe<Array<Maybe<HomePageFeatureShowcaseSlides>>>;
};

export type HomePageProjectsSection = {
  __typename?: 'HomePageProjectsSection';
  eyebrow: Scalars['String']['output'];
};

export type HomePageServicesSectionItems = {
  __typename?: 'HomePageServicesSectionItems';
  title: Scalars['String']['output'];
  content: Scalars['String']['output'];
};

export type HomePageServicesSection = {
  __typename?: 'HomePageServicesSection';
  eyebrow: Scalars['String']['output'];
  items?: Maybe<Array<Maybe<HomePageServicesSectionItems>>>;
};

export type HomePageTestimonialsSection = {
  __typename?: 'HomePageTestimonialsSection';
  curvedHeading: Scalars['String']['output'];
};

export type HomePageBlogSection = {
  __typename?: 'HomePageBlogSection';
  eyebrow: Scalars['String']['output'];
  heading: Scalars['String']['output'];
};

export type HomePage = Node & Document & {
  __typename?: 'HomePage';
  hero?: Maybe<HomePageHero>;
  featureShowcase?: Maybe<HomePageFeatureShowcase>;
  projectsSection?: Maybe<HomePageProjectsSection>;
  servicesSection?: Maybe<HomePageServicesSection>;
  testimonialsSection?: Maybe<HomePageTestimonialsSection>;
  blogSection?: Maybe<HomePageBlogSection>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomePageHeroFilter = {
  mobileHeadline?: InputMaybe<StringFilter>;
  curvedHeadline?: InputMaybe<StringFilter>;
  eyebrow?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  primaryCtaLabel?: InputMaybe<StringFilter>;
  primaryCtaUrl?: InputMaybe<StringFilter>;
};

export type HomePageFeatureShowcaseSlidesFilter = {
  image?: InputMaybe<ImageFilter>;
  title?: InputMaybe<StringFilter>;
};

export type HomePageFeatureShowcaseFilter = {
  headingPrefix?: InputMaybe<StringFilter>;
  highlightWord?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  slides?: InputMaybe<HomePageFeatureShowcaseSlidesFilter>;
};

export type HomePageProjectsSectionFilter = {
  eyebrow?: InputMaybe<StringFilter>;
};

export type HomePageServicesSectionItemsFilter = {
  title?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
};

export type HomePageServicesSectionFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  items?: InputMaybe<HomePageServicesSectionItemsFilter>;
};

export type HomePageTestimonialsSectionFilter = {
  curvedHeading?: InputMaybe<StringFilter>;
};

export type HomePageBlogSectionFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
};

export type HomePageFilter = {
  hero?: InputMaybe<HomePageHeroFilter>;
  featureShowcase?: InputMaybe<HomePageFeatureShowcaseFilter>;
  projectsSection?: InputMaybe<HomePageProjectsSectionFilter>;
  servicesSection?: InputMaybe<HomePageServicesSectionFilter>;
  testimonialsSection?: InputMaybe<HomePageTestimonialsSectionFilter>;
  blogSection?: InputMaybe<HomePageBlogSectionFilter>;
};

export type HomePageConnectionEdges = {
  __typename?: 'HomePageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<HomePage>;
};

export type HomePageConnection = Connection & {
  __typename?: 'HomePageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomePageConnectionEdges>>>;
};

export type Project = Node & Document & {
  __typename?: 'Project';
  order: Scalars['Float']['output'];
  company: Scalars['String']['output'];
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  image: Scalars['String']['output'];
  video?: Maybe<Scalars['String']['output']>;
  href: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ProjectFilter = {
  order?: InputMaybe<NumberFilter>;
  company?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  video?: InputMaybe<ImageFilter>;
  href?: InputMaybe<StringFilter>;
};

export type ProjectConnectionEdges = {
  __typename?: 'ProjectConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Project>;
};

export type ProjectConnection = Connection & {
  __typename?: 'ProjectConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectConnectionEdges>>>;
};

export type Testimonial = Node & Document & {
  __typename?: 'Testimonial';
  order: Scalars['Float']['output'];
  author: Scalars['String']['output'];
  company: Scalars['String']['output'];
  quote: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TestimonialFilter = {
  order?: InputMaybe<NumberFilter>;
  author?: InputMaybe<StringFilter>;
  company?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
};

export type TestimonialConnectionEdges = {
  __typename?: 'TestimonialConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonial>;
};

export type TestimonialConnection = Connection & {
  __typename?: 'TestimonialConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimonialConnectionEdges>>>;
};

export type Post = Node & Document & {
  __typename?: 'Post';
  title: Scalars['String']['output'];
  excerpt: Scalars['String']['output'];
  meta: Scalars['String']['output'];
  coverImage: Scalars['String']['output'];
  publishedAt: Scalars['String']['output'];
  link?: Maybe<Scalars['String']['output']>;
  body: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PostFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  meta?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  publishedAt?: InputMaybe<DatetimeFilter>;
  link?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PostConnectionEdges = {
  __typename?: 'PostConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Post>;
};

export type PostConnection = Connection & {
  __typename?: 'PostConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePassword: Scalars['Boolean']['output'];
  updateUser: User;
  createUser: User;
  updateSiteSettings: SiteSettings;
  createSiteSettings: SiteSettings;
  updateHomePage: HomePage;
  createHomePage: HomePage;
  updateProject: Project;
  createProject: Project;
  updateTestimonial: Testimonial;
  createTestimonial: Testimonial;
  updatePost: Post;
  createPost: Post;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePasswordArgs = {
  password: Scalars['String']['input'];
};


export type MutationUpdateUserArgs = {
  relativePath: Scalars['String']['input'];
  params: UserMutation;
};


export type MutationCreateUserArgs = {
  relativePath: Scalars['String']['input'];
  params: UserMutation;
};


export type MutationUpdateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationCreateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationUpdateHomePageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageMutation;
};


export type MutationCreateHomePageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageMutation;
};


export type MutationUpdateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationCreateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationUpdateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};


export type MutationCreateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};


export type MutationUpdatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationCreatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};

export type DocumentUpdateMutation = {
  user?: InputMaybe<UserMutation>;
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  homePage?: InputMaybe<HomePageMutation>;
  project?: InputMaybe<ProjectMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
  post?: InputMaybe<PostMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  user?: InputMaybe<UserMutation>;
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  homePage?: InputMaybe<HomePageMutation>;
  project?: InputMaybe<ProjectMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
  post?: InputMaybe<PostMutation>;
};

export type UserUsersPasswordMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  passwordChangeRequired: Scalars['Boolean']['input'];
};

export type UserUsersMutation = {
  username?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  password?: InputMaybe<UserUsersPasswordMutation>;
};

export type UserMutation = {
  users?: InputMaybe<Array<InputMaybe<UserUsersMutation>>>;
};

export type SiteSettingsNavItemsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsNavCtaMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsFooterPrimaryCtaMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsSocialLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsMutation = {
  siteName?: InputMaybe<Scalars['String']['input']>;
  siteUrl?: InputMaybe<Scalars['String']['input']>;
  defaultTitle?: InputMaybe<Scalars['String']['input']>;
  titleTemplate?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  abstract?: InputMaybe<Scalars['String']['input']>;
  keywords?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  creator?: InputMaybe<Scalars['String']['input']>;
  publisher?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  themeColor?: InputMaybe<Scalars['String']['input']>;
  ogImage?: InputMaybe<Scalars['String']['input']>;
  twitterHandle?: InputMaybe<Scalars['String']['input']>;
  navItems?: InputMaybe<Array<InputMaybe<SiteSettingsNavItemsMutation>>>;
  navCta?: InputMaybe<SiteSettingsNavCtaMutation>;
  footerMarqueeText?: InputMaybe<Scalars['String']['input']>;
  footerPrimaryCta?: InputMaybe<SiteSettingsFooterPrimaryCtaMutation>;
  socialLinks?: InputMaybe<Array<InputMaybe<SiteSettingsSocialLinksMutation>>>;
  footerCopyright?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageHeroMutation = {
  mobileHeadline?: InputMaybe<Scalars['String']['input']>;
  curvedHeadline?: InputMaybe<Scalars['String']['input']>;
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  primaryCtaLabel?: InputMaybe<Scalars['String']['input']>;
  primaryCtaUrl?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageFeatureShowcaseSlidesMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageFeatureShowcaseMutation = {
  headingPrefix?: InputMaybe<Scalars['String']['input']>;
  highlightWord?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  slides?: InputMaybe<Array<InputMaybe<HomePageFeatureShowcaseSlidesMutation>>>;
};

export type HomePageProjectsSectionMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageServicesSectionItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageServicesSectionMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<HomePageServicesSectionItemsMutation>>>;
};

export type HomePageTestimonialsSectionMutation = {
  curvedHeading?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageBlogSectionMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageMutation = {
  hero?: InputMaybe<HomePageHeroMutation>;
  featureShowcase?: InputMaybe<HomePageFeatureShowcaseMutation>;
  projectsSection?: InputMaybe<HomePageProjectsSectionMutation>;
  servicesSection?: InputMaybe<HomePageServicesSectionMutation>;
  testimonialsSection?: InputMaybe<HomePageTestimonialsSectionMutation>;
  blogSection?: InputMaybe<HomePageBlogSectionMutation>;
};

export type ProjectMutation = {
  order?: InputMaybe<Scalars['Float']['input']>;
  company?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  video?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type TestimonialMutation = {
  order?: InputMaybe<Scalars['Float']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  company?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
};

export type PostMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  meta?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  publishedAt?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type UserPartsFragment = { __typename: 'User', users?: Array<{ __typename: 'UserUsers', username: string, name?: string | null, email?: string | null, password: { __typename?: 'UserUsersPassword', value: string, passwordChangeRequired?: boolean | null } } | null> | null };

export type SiteSettingsPartsFragment = { __typename: 'SiteSettings', siteName: string, siteUrl: string, defaultTitle: string, titleTemplate: string, description: string, abstract: string, keywords: Array<string>, creator: string, publisher: string, category: string, themeColor: string, ogImage: string, twitterHandle: string, footerMarqueeText: string, footerCopyright: string, navItems?: Array<{ __typename: 'SiteSettingsNavItems', label: string, href: string } | null> | null, navCta?: { __typename: 'SiteSettingsNavCta', label: string, href: string } | null, footerPrimaryCta?: { __typename: 'SiteSettingsFooterPrimaryCta', label: string, url: string } | null, socialLinks?: Array<{ __typename: 'SiteSettingsSocialLinks', label: string, url: string } | null> | null };

export type HomePagePartsFragment = { __typename: 'HomePage', hero?: { __typename: 'HomePageHero', mobileHeadline: string, curvedHeadline: string, eyebrow: string, description: string, primaryCtaLabel: string, primaryCtaUrl: string } | null, featureShowcase?: { __typename: 'HomePageFeatureShowcase', headingPrefix: string, highlightWord: string, description: string, slides?: Array<{ __typename: 'HomePageFeatureShowcaseSlides', image: string, title: string } | null> | null } | null, projectsSection?: { __typename: 'HomePageProjectsSection', eyebrow: string } | null, servicesSection?: { __typename: 'HomePageServicesSection', eyebrow: string, items?: Array<{ __typename: 'HomePageServicesSectionItems', title: string, content: string } | null> | null } | null, testimonialsSection?: { __typename: 'HomePageTestimonialsSection', curvedHeading: string } | null, blogSection?: { __typename: 'HomePageBlogSection', eyebrow: string, heading: string } | null };

export type ProjectPartsFragment = { __typename: 'Project', order: number, company: string, title: string, date: string, image: string, video?: string | null, href: string };

export type TestimonialPartsFragment = { __typename: 'Testimonial', order: number, author: string, company: string, quote: string };

export type PostPartsFragment = { __typename: 'Post', title: string, excerpt: string, meta: string, coverImage: string, publishedAt: string, link?: string | null, body: any };

export type UserQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type UserQuery = { __typename?: 'Query', user: { __typename: 'User', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, users?: Array<{ __typename: 'UserUsers', username: string, name?: string | null, email?: string | null, password: { __typename?: 'UserUsersPassword', value: string, passwordChangeRequired?: boolean | null } } | null> | null } };

export type UserConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<UserFilter>;
}>;


export type UserConnectionQuery = { __typename?: 'Query', userConnection: { __typename?: 'UserConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'UserConnectionEdges', cursor: string, node?: { __typename: 'User', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, users?: Array<{ __typename: 'UserUsers', username: string, name?: string | null, email?: string | null, password: { __typename?: 'UserUsersPassword', value: string, passwordChangeRequired?: boolean | null } } | null> | null } | null } | null> | null } };

export type SiteSettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteSettingsQuery = { __typename?: 'Query', siteSettings: { __typename: 'SiteSettings', id: string, siteName: string, siteUrl: string, defaultTitle: string, titleTemplate: string, description: string, abstract: string, keywords: Array<string>, creator: string, publisher: string, category: string, themeColor: string, ogImage: string, twitterHandle: string, footerMarqueeText: string, footerCopyright: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navItems?: Array<{ __typename: 'SiteSettingsNavItems', label: string, href: string } | null> | null, navCta?: { __typename: 'SiteSettingsNavCta', label: string, href: string } | null, footerPrimaryCta?: { __typename: 'SiteSettingsFooterPrimaryCta', label: string, url: string } | null, socialLinks?: Array<{ __typename: 'SiteSettingsSocialLinks', label: string, url: string } | null> | null } };

export type SiteSettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
}>;


export type SiteSettingsConnectionQuery = { __typename?: 'Query', siteSettingsConnection: { __typename?: 'SiteSettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteSettingsConnectionEdges', cursor: string, node?: { __typename: 'SiteSettings', id: string, siteName: string, siteUrl: string, defaultTitle: string, titleTemplate: string, description: string, abstract: string, keywords: Array<string>, creator: string, publisher: string, category: string, themeColor: string, ogImage: string, twitterHandle: string, footerMarqueeText: string, footerCopyright: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navItems?: Array<{ __typename: 'SiteSettingsNavItems', label: string, href: string } | null> | null, navCta?: { __typename: 'SiteSettingsNavCta', label: string, href: string } | null, footerPrimaryCta?: { __typename: 'SiteSettingsFooterPrimaryCta', label: string, url: string } | null, socialLinks?: Array<{ __typename: 'SiteSettingsSocialLinks', label: string, url: string } | null> | null } | null } | null> | null } };

export type HomePageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomePageQuery = { __typename?: 'Query', homePage: { __typename: 'HomePage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomePageHero', mobileHeadline: string, curvedHeadline: string, eyebrow: string, description: string, primaryCtaLabel: string, primaryCtaUrl: string } | null, featureShowcase?: { __typename: 'HomePageFeatureShowcase', headingPrefix: string, highlightWord: string, description: string, slides?: Array<{ __typename: 'HomePageFeatureShowcaseSlides', image: string, title: string } | null> | null } | null, projectsSection?: { __typename: 'HomePageProjectsSection', eyebrow: string } | null, servicesSection?: { __typename: 'HomePageServicesSection', eyebrow: string, items?: Array<{ __typename: 'HomePageServicesSectionItems', title: string, content: string } | null> | null } | null, testimonialsSection?: { __typename: 'HomePageTestimonialsSection', curvedHeading: string } | null, blogSection?: { __typename: 'HomePageBlogSection', eyebrow: string, heading: string } | null } };

export type HomePageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageFilter>;
}>;


export type HomePageConnectionQuery = { __typename?: 'Query', homePageConnection: { __typename?: 'HomePageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomePageConnectionEdges', cursor: string, node?: { __typename: 'HomePage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomePageHero', mobileHeadline: string, curvedHeadline: string, eyebrow: string, description: string, primaryCtaLabel: string, primaryCtaUrl: string } | null, featureShowcase?: { __typename: 'HomePageFeatureShowcase', headingPrefix: string, highlightWord: string, description: string, slides?: Array<{ __typename: 'HomePageFeatureShowcaseSlides', image: string, title: string } | null> | null } | null, projectsSection?: { __typename: 'HomePageProjectsSection', eyebrow: string } | null, servicesSection?: { __typename: 'HomePageServicesSection', eyebrow: string, items?: Array<{ __typename: 'HomePageServicesSectionItems', title: string, content: string } | null> | null } | null, testimonialsSection?: { __typename: 'HomePageTestimonialsSection', curvedHeading: string } | null, blogSection?: { __typename: 'HomePageBlogSection', eyebrow: string, heading: string } | null } | null } | null> | null } };

export type ProjectQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectQuery = { __typename?: 'Query', project: { __typename: 'Project', id: string, order: number, company: string, title: string, date: string, image: string, video?: string | null, href: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProjectConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
}>;


export type ProjectConnectionQuery = { __typename?: 'Query', projectConnection: { __typename?: 'ProjectConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectConnectionEdges', cursor: string, node?: { __typename: 'Project', id: string, order: number, company: string, title: string, date: string, image: string, video?: string | null, href: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TestimonialQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TestimonialQuery = { __typename?: 'Query', testimonial: { __typename: 'Testimonial', id: string, order: number, author: string, company: string, quote: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TestimonialConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialFilter>;
}>;


export type TestimonialConnectionQuery = { __typename?: 'Query', testimonialConnection: { __typename?: 'TestimonialConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TestimonialConnectionEdges', cursor: string, node?: { __typename: 'Testimonial', id: string, order: number, author: string, company: string, quote: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PostQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PostQuery = { __typename?: 'Query', post: { __typename: 'Post', id: string, title: string, excerpt: string, meta: string, coverImage: string, publishedAt: string, link?: string | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PostConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
}>;


export type PostConnectionQuery = { __typename?: 'Query', postConnection: { __typename?: 'PostConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PostConnectionEdges', cursor: string, node?: { __typename: 'Post', id: string, title: string, excerpt: string, meta: string, coverImage: string, publishedAt: string, link?: string | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const UserPartsFragmentDoc = gql`
    fragment UserParts on User {
  __typename
  users {
    __typename
    username
    name
    email
    password {
      value
      passwordChangeRequired
    }
  }
}
    `;
export const SiteSettingsPartsFragmentDoc = gql`
    fragment SiteSettingsParts on SiteSettings {
  __typename
  siteName
  siteUrl
  defaultTitle
  titleTemplate
  description
  abstract
  keywords
  creator
  publisher
  category
  themeColor
  ogImage
  twitterHandle
  navItems {
    __typename
    label
    href
  }
  navCta {
    __typename
    label
    href
  }
  footerMarqueeText
  footerPrimaryCta {
    __typename
    label
    url
  }
  socialLinks {
    __typename
    label
    url
  }
  footerCopyright
}
    `;
export const HomePagePartsFragmentDoc = gql`
    fragment HomePageParts on HomePage {
  __typename
  hero {
    __typename
    mobileHeadline
    curvedHeadline
    eyebrow
    description
    primaryCtaLabel
    primaryCtaUrl
  }
  featureShowcase {
    __typename
    headingPrefix
    highlightWord
    description
    slides {
      __typename
      image
      title
    }
  }
  projectsSection {
    __typename
    eyebrow
  }
  servicesSection {
    __typename
    eyebrow
    items {
      __typename
      title
      content
    }
  }
  testimonialsSection {
    __typename
    curvedHeading
  }
  blogSection {
    __typename
    eyebrow
    heading
  }
}
    `;
export const ProjectPartsFragmentDoc = gql`
    fragment ProjectParts on Project {
  __typename
  order
  company
  title
  date
  image
  video
  href
}
    `;
export const TestimonialPartsFragmentDoc = gql`
    fragment TestimonialParts on Testimonial {
  __typename
  order
  author
  company
  quote
}
    `;
export const PostPartsFragmentDoc = gql`
    fragment PostParts on Post {
  __typename
  title
  excerpt
  meta
  coverImage
  publishedAt
  link
  body
}
    `;
export const UserDocument = gql`
    query user($relativePath: String!) {
  user(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...UserParts
  }
}
    ${UserPartsFragmentDoc}`;
export const UserConnectionDocument = gql`
    query userConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: UserFilter) {
  userConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...UserParts
      }
    }
  }
}
    ${UserPartsFragmentDoc}`;
export const SiteSettingsDocument = gql`
    query siteSettings($relativePath: String!) {
  siteSettings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteSettingsParts
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const SiteSettingsConnectionDocument = gql`
    query siteSettingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteSettingsFilter) {
  siteSettingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteSettingsParts
      }
    }
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const HomePageDocument = gql`
    query homePage($relativePath: String!) {
  homePage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomePageParts
  }
}
    ${HomePagePartsFragmentDoc}`;
export const HomePageConnectionDocument = gql`
    query homePageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomePageFilter) {
  homePageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomePageParts
      }
    }
  }
}
    ${HomePagePartsFragmentDoc}`;
export const ProjectDocument = gql`
    query project($relativePath: String!) {
  project(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectParts
  }
}
    ${ProjectPartsFragmentDoc}`;
export const ProjectConnectionDocument = gql`
    query projectConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectFilter) {
  projectConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectParts
      }
    }
  }
}
    ${ProjectPartsFragmentDoc}`;
export const TestimonialDocument = gql`
    query testimonial($relativePath: String!) {
  testimonial(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimonialParts
  }
}
    ${TestimonialPartsFragmentDoc}`;
export const TestimonialConnectionDocument = gql`
    query testimonialConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimonialFilter) {
  testimonialConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimonialParts
      }
    }
  }
}
    ${TestimonialPartsFragmentDoc}`;
export const PostDocument = gql`
    query post($relativePath: String!) {
  post(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostParts
  }
}
    ${PostPartsFragmentDoc}`;
export const PostConnectionDocument = gql`
    query postConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostFilter) {
  postConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostParts
      }
    }
  }
}
    ${PostPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      user(variables: UserQueryVariables, options?: C): Promise<{data: UserQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UserQueryVariables, query: string}> {
        return requester<{data: UserQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UserQueryVariables, query: string}, UserQueryVariables>(UserDocument, variables, options);
      },
    userConnection(variables?: UserConnectionQueryVariables, options?: C): Promise<{data: UserConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UserConnectionQueryVariables, query: string}> {
        return requester<{data: UserConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UserConnectionQueryVariables, query: string}, UserConnectionQueryVariables>(UserConnectionDocument, variables, options);
      },
    siteSettings(variables: SiteSettingsQueryVariables, options?: C): Promise<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}> {
        return requester<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}, SiteSettingsQueryVariables>(SiteSettingsDocument, variables, options);
      },
    siteSettingsConnection(variables?: SiteSettingsConnectionQueryVariables, options?: C): Promise<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}, SiteSettingsConnectionQueryVariables>(SiteSettingsConnectionDocument, variables, options);
      },
    homePage(variables: HomePageQueryVariables, options?: C): Promise<{data: HomePageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageQueryVariables, query: string}> {
        return requester<{data: HomePageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageQueryVariables, query: string}, HomePageQueryVariables>(HomePageDocument, variables, options);
      },
    homePageConnection(variables?: HomePageConnectionQueryVariables, options?: C): Promise<{data: HomePageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageConnectionQueryVariables, query: string}> {
        return requester<{data: HomePageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageConnectionQueryVariables, query: string}, HomePageConnectionQueryVariables>(HomePageConnectionDocument, variables, options);
      },
    project(variables: ProjectQueryVariables, options?: C): Promise<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}> {
        return requester<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}, ProjectQueryVariables>(ProjectDocument, variables, options);
      },
    projectConnection(variables?: ProjectConnectionQueryVariables, options?: C): Promise<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}, ProjectConnectionQueryVariables>(ProjectConnectionDocument, variables, options);
      },
    testimonial(variables: TestimonialQueryVariables, options?: C): Promise<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}> {
        return requester<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}, TestimonialQueryVariables>(TestimonialDocument, variables, options);
      },
    testimonialConnection(variables?: TestimonialConnectionQueryVariables, options?: C): Promise<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}> {
        return requester<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}, TestimonialConnectionQueryVariables>(TestimonialConnectionDocument, variables, options);
      },
    post(variables: PostQueryVariables, options?: C): Promise<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}> {
        return requester<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}, PostQueryVariables>(PostDocument, variables, options);
      },
    postConnection(variables?: PostConnectionQueryVariables, options?: C): Promise<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}> {
        return requester<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}, PostConnectionQueryVariables>(PostConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "/api/tina/gql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  